version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100"



command:
  build:
    - npm install


  dev:
    - "npm run watch &"

  killall:
    killall jekyll
